spring:
  datasource:
    url: jdbc:mysql://bywxnlgjwbxcr3at3a6x-mysql.services.clever-cloud.com:3306/bywxnlgjwbxcr3at3a6x
    username: ugce10d7uezxuvt0
    password: 9G1vgV6bXvzo1DnSWB7G
#    url: jdbc:mysql://localhost:3306/PQRS
 #   username: root
  #  password: Osoted12.
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080